### ISSUE TITLE
run error "Audio source"

### ISSUE THREAD

**Issue by loganbaba111** [SevaSk/ecoute#101]
![image](https://github.com/SevaSk/ecoute/assets/135634119/f1cb0224-c334-4105-a225-b8e255ec5125)

C:\Users\loganbaba\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
Traceback (most recent call last):
  File "C:\Program Files\ecoute\AudioRecorder.py", line 24, in adjust_for_noise
    self.recorder.adjust_for_ambient_noise(self.source)
  File "C:\Program Files\ecoute\custom_speech_recognition\__init__.py", line 399, in adjust_for_ambient_noise
    assert source.stream is not None, "Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
AssertionError: Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ecoute\main.py", line 128, in <module>
    main()
  File "C:\Program Files\ecoute\main.py", line 85, in main
    speaker_audio_recorder = AudioRecorder.DefaultSpeakerRecorder()
  File "C:\Program Files\ecoute\AudioRecorder.py", line 59, in __init__
    self.adjust_for_noise("Default Speaker", "Please make or play some noise from the Default Speaker...")
  File "C:\Program Files\ecoute\AudioRecorder.py", line 23, in adjust_for_noise
    with self.source:
  File "C:\Program Files\ecoute\custom_speech_recognition\__init__.py", line 205, in __exit__
    self.stream.close()
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by jinnnnnnnnnsd** [comment]
> ![图像](https://user-images.githubusercontent.com/135634119/245213573-f1cb0224-c334-4105-a225-b8e255ec5125.png)
> 
> C:\Users\loganbaba\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: 'nopython' 关键字参数未提供给 'numba.jit' 装饰器。此参数的隐式默认值当前为 False，但在 Numba 0.59.0 中将更改为 True。有关详细信息，请参阅https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit。 def backtrace(trace: np.ndarray): [INFO] 调整默认麦克风的环境噪音。请从默认麦克风中发出一些噪音... [INFO] 已完成默认麦克风的环境噪音调整。 [INFO] 调整默认扬声器的环境噪音。请从默认扬声器发出或播放一些噪音... 回溯（最近一次调用最后一次）： 文件“C:\Program Files\ecoute\AudioRecorder.py”，第 24 行，在 adjustment_for_noise self.recorder.adjust_for_ambient_noise(self.source) 文件“C:\Program Files\ecoute\custom_speech_recognition_ _init”_ _.py”，第 399 行，在 adjustment_for_ambient_noise 中 断言 source.stream 不是 None，“在调整之前必须输入音频源，请参阅文档；您是否在语句之外`AudioSource`使用？” AssertionError：调整前必须输入音频源，请参阅文档；您在声明之外使用吗？`source``with``AudioSource``source``with`
> 
> 在处理上述异常的过程中，又出现了一个异常：
> 
> 回溯（最近一次调用最后）： 文件“C：\ Program Files \ ecoute \ main.py”，第128行，在 main（）中 文件“C：\ Program Files \ ecoute \ main.py”，第85行，在main中 peaker_audio_recorder = AudioRecorder.DefaultSpeakerRecorder() 文件 "C:\Program Files\ecoute\AudioRecorder.py", 第 59 行, **init** self.adjust_for_noise("默认扬声器", "请从默认扬声器发出或播放一些噪音... ") 文件 "C:\Program Files\ecute\AudioRecorder.py"，第 23 行，在 adjustment_for_noise 中 使用 self.source： 文件 "C:\Program Files\ecout\custom_speech_recognition_ _init_ _.py"，第 205 行，在**退出** self中.stream.close() 属性错误：“NoneType”对象没有属性“close”

I also encountered the problem of consent, did you finally solve it?

**Comment by vivekuppal** [comment]
@loganbaba111 you can attempt to try out https://github.com/vivekuppal/transcribe
It is fork of this repo, has the same functionality as in ecoute and some enhancements.
I believe I had this issue and it was resolved in one of the PRs.

**Comment by jinnnnnnnnnsd** [comment]
> @loganbaba111 you can attempt to try out https://github.com/vivekuppal/transcribe It is fork of this repo, has the same functionality as in ecoute and some enhancements. I believe I had this issue in transcribe and it was resolved in one of the PRs.

I still have the same problem. Have you re-downloaded the requirement.txt file? Because it is already available in transcript

**Comment by vivekuppal** [comment]
The issue you are encountering is in the file
`custom_speech_recognition\__init__.py`

in the class

`class Microphone(AudioSource):`

in the method
```
    def __enter__(self):
        assert self.stream is None, "This audio source is already inside a context manager"
        self.audio = self.pyaudio_module.PyAudio()

        try:
            if self.speaker:
                p = self.audio
                self.stream = Microphone.MicrophoneStream(
                    p.open(
                        input_device_index=self.device_index,
                        channels=self.channels,
                        format=self.format,
                        rate=self.SAMPLE_RATE,
                        frames_per_buffer=self.CHUNK,
                        input=True
                    )
                )
            else:
                self.stream = Microphone.MicrophoneStream(
                    self.audio.open(
                        input_device_index=self.device_index, channels=1, format=self.format,
                        rate=self.SAMPLE_RATE, frames_per_buffer=self.CHUNK, input=True,
                    )
                )
        except Exception:
            self.audio.terminate()
        return self
```

An exception is being thrown in `p.open` method.
You would want to capture and print the details of the exception to further understand the root cause of the issue at hand.
